// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Resp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReqSignup struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignup) Reset()         { *m = ReqSignup{} }
func (m *ReqSignup) String() string { return proto.CompactTextString(m) }
func (*ReqSignup) ProtoMessage()    {}
func (*ReqSignup) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ReqSignup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignup.Unmarshal(m, b)
}
func (m *ReqSignup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignup.Marshal(b, m, deterministic)
}
func (m *ReqSignup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignup.Merge(m, src)
}
func (m *ReqSignup) XXX_Size() int {
	return xxx_messageInfo_ReqSignup.Size(m)
}
func (m *ReqSignup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignup proto.InternalMessageInfo

func (m *ReqSignup) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReqSignup) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type ReqSignin struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignin) Reset()         { *m = ReqSignin{} }
func (m *ReqSignin) String() string { return proto.CompactTextString(m) }
func (*ReqSignin) ProtoMessage()    {}
func (*ReqSignin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ReqSignin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignin.Unmarshal(m, b)
}
func (m *ReqSignin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignin.Marshal(b, m, deterministic)
}
func (m *ReqSignin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignin.Merge(m, src)
}
func (m *ReqSignin) XXX_Size() int {
	return xxx_messageInfo_ReqSignin.Size(m)
}
func (m *ReqSignin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignin proto.InternalMessageInfo

func (m *ReqSignin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReqSignin) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type ReqUserInfo struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserInfo) Reset()         { *m = ReqUserInfo{} }
func (m *ReqUserInfo) String() string { return proto.CompactTextString(m) }
func (*ReqUserInfo) ProtoMessage()    {}
func (*ReqUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ReqUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserInfo.Unmarshal(m, b)
}
func (m *ReqUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserInfo.Marshal(b, m, deterministic)
}
func (m *ReqUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserInfo.Merge(m, src)
}
func (m *ReqUserInfo) XXX_Size() int {
	return xxx_messageInfo_ReqUserInfo.Size(m)
}
func (m *ReqUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserInfo proto.InternalMessageInfo

func (m *ReqUserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReqUserInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Resp)(nil), "go.micro.service.user.Resp")
	proto.RegisterType((*ReqSignup)(nil), "go.micro.service.user.ReqSignup")
	proto.RegisterType((*ReqSignin)(nil), "go.micro.service.user.ReqSignin")
	proto.RegisterType((*ReqUserInfo)(nil), "go.micro.service.user.ReqUserInfo")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x70, 0x63, 0xff, 0xe0, 0x4e, 0x3d, 0x48, 0x50, 0x58, 0xea, 0x65, 0xd9, 0xd3, 0x9e,
	0x72, 0xd0, 0x07, 0x50, 0xa8, 0x97, 0x1e, 0x2a, 0x92, 0x2a, 0x9e, 0xd7, 0x76, 0x5c, 0x82, 0x34,
	0x93, 0x66, 0x5a, 0x1f, 0xdc, 0x27, 0x90, 0x24, 0xdb, 0xc5, 0x83, 0x75, 0xc1, 0xdb, 0x0c, 0xf9,
	0xf8, 0xc1, 0x37, 0x04, 0x60, 0xcf, 0xe8, 0x95, 0xf3, 0xb4, 0x23, 0x79, 0xd5, 0x90, 0xda, 0x98,
	0x95, 0x27, 0xc5, 0xe8, 0x3f, 0xcd, 0x0a, 0x55, 0x78, 0x2c, 0xef, 0x61, 0xa8, 0x91, 0x9d, 0x94,
	0x30, 0x9c, 0xd1, 0x1a, 0x73, 0x51, 0x88, 0x6a, 0xa4, 0xe3, 0x2c, 0x2f, 0x60, 0xb0, 0xe0, 0x26,
	0x3f, 0x2d, 0x44, 0x95, 0xe9, 0x30, 0x86, 0xd4, 0x43, 0xbd, 0xab, 0xf3, 0x41, 0x21, 0xaa, 0x73,
	0x1d, 0xe7, 0x72, 0x06, 0x99, 0xc6, 0xed, 0xd2, 0x34, 0x76, 0xef, 0xe4, 0x14, 0xce, 0x5e, 0x18,
	0xfd, 0x63, 0xbd, 0x49, 0x54, 0xa6, 0xbb, 0x3d, 0xbc, 0x3d, 0xd5, 0xcc, 0xaf, 0xe4, 0xd7, 0xad,
	0xd9, 0xed, 0x3f, 0x10, 0x63, 0xff, 0x8d, 0xdc, 0xc1, 0x44, 0xe3, 0x36, 0x44, 0xe7, 0xf6, 0x9d,
	0xfe, 0x64, 0x2e, 0x61, 0xf4, 0x4c, 0x1f, 0x68, 0x5b, 0x23, 0x2d, 0x37, 0x5f, 0x02, 0x26, 0x21,
	0xb2, 0x4c, 0x17, 0x92, 0x73, 0x18, 0xb7, 0xbd, 0x0a, 0xf5, 0xeb, 0xf9, 0x54, 0xd7, 0x7c, 0x7a,
	0x7d, 0x34, 0xc1, 0xae, 0x3c, 0x39, 0x50, 0xc6, 0xf6, 0x51, 0xc6, 0xf6, 0x51, 0x8b, 0xd4, 0x2b,
	0x76, 0x2c, 0x8f, 0x63, 0x87, 0x4c, 0x0f, 0xf7, 0x36, 0x8e, 0xff, 0xe3, 0xf6, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x83, 0x62, 0xfe, 0x57, 0x2d, 0x02, 0x00, 0x00,
}
